api/urls.py
from django.urls import path

from api import views

app_name = "api"


urlpatterns = [
    ##### CLIENTS #####
    path('ws/grantgoal/list', views.wsListGrantGoal, name="ws_grantgoal"),
    path('client/grantgoal/create/', views.CreateGrantGoalClient.as_view(), name="client_grantgoal_create"),
    path('client/grantgoal/', views.ListGrantGoalClient.as_view(), name="client_grantgoal"),
    path('client/grantgoal/detail/<str:gname>/', views.DetailGrantGoalClient.as_view(), name="client_detail"),
    path('client/grantgoal/update/<int:pk>/', views.UpdateGrantGoalClient.as_view(), name="client_update"),

    ###### V2 API #####
    path('v3/create/grantgoal/', views.CreateGrantGoal.as_view(), name="create_grantgoal"),
    path('v2/list/grant_goals/', views.ListGrantGoal.as_view(), name="list_grantgoals"),
    path('v2/detail/grant_goal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_grantgoal"),
    path('v3/update/grant_goal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_grantgoal"),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"


urlpatterns = [
    
    path('new_grant_goal/', views.NewGrantGoal.as_view(), name="new_grant_goal"),
    path('update_grant_goal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_grant_goal"),
    path('detail_grant_goal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_grant_goal"),
    path('delete_grant_goal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="delete_grant_goal"),
    #### GOAL'S URLS
    path('goal/list/', views.ListGoal.as_view(), name="list_goal"),
    path('goal/detail/<int:pk>/', views.DetailGoal.as_view(), name="detail_goal"),

    ### FULL CALENDAR URL'S
    path('fullcalendar/', views.FullCalendarGG.as_view(), name="fullcalendar"),

    #### AUTHENTICATE SYSTEM URLS ####
    path('logout/', views.Logout.as_view(), name="logout"),
    path('', views.Index.as_view(), name="index"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

sysplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('api/', include("api.urls")),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from api.models import GrantGoal

class UserForm(UserCreationForm):
    username = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Username"})) 
    password1 = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Escribe tu Password"}))
    password2 = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Confirma tu Password"}))  
    first_name = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu First Name"})) 
    last_name = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Last Name"})) 
    email = forms.EmailField(max_length=32, widget=forms.EmailInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Email"})) 


class GrantGoalForm(forms.ModelForm):
    class Meta:
        model = GrantGoal
        fields = [
            "user",
            "goal_title",
            "description",
            "days_duration",
            "state",
            "sprint",
            "slug"
        ]
        widgets = {
            "user": forms.Select(attrs={"class":"form-select", "placeholder": "Seleccione un User"}),
            "goal_title": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Nombre del Grant Goal"}),
            "description": forms.Textarea(attrs={"class":"form-control", "cols":"5", "type":"text"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-select"}),
            "sprint": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control"})
        }


class UpdateGrantGoalForm(forms.ModelForm):
    class Meta:
        model = GrantGoal
        fields = [
            "user",
            "goal_title",
            "description",
            "final_date",
            "status",
            "slug"
        ]
        widgets = {
            "user": forms.Select(attrs={"class": "form-select"}),
            "goal_title": forms.TextInput(attrs={"class": "form-control", "placeholder": "Escribe el nombre del grant goal"}),
            "description": forms.Textarea(attrs={"class":"form-control", "cols":"5", "type":"text"}),
            "final_date": forms.DateInput(attrs={"type": "date", "class": "form-control"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-select"}),
            "sprint": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control"})
        }





class LoginForm(forms.Form):
    username = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Username"}))
    password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Escribe tu Password"}))

home/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.messages.views import SuccessMessageMixin

from api.models import GrantGoal, Goal
from .forms import GrantGoalForm, UpdateGrantGoalForm, LoginForm, UserForm
# Create your views here.

############## GRANT GOAL CRUD ##############

## List
class Index(generic.View):
    template_name = "home/index.html"
    context = {}
    form_class = LoginForm


    def get(self, request, *args, **kwargs):
        self.context = {
            "grant_goals": GrantGoal.objects.filter(status=True),
            "form": self.form_class 
        }
        return render(request, self.template_name, self.context)

    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("home:index")
        else:
            return redirect("home:index")






## DEtail
class DetailGrantGoal(generic.View):
    template_name = "home/detail_grant_goal.html"
    context = {}

    def get(self, request, pk, *args, **kwargs):
        self.context = {
            "grant_goal": GrantGoal.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)



##Create
class NewGrantGoal(SuccessMessageMixin, generic.CreateView):
    template_name = "home/new_grantgoal.html"
    model = GrantGoal
    form_class = GrantGoalForm
    success_url = reverse_lazy("home:new_grant_goal")
    success_message = "The New Grant Goal Was Created! ..."


    
    
## Update
class UpdateGrantGoal(SuccessMessageMixin, generic.UpdateView):
    template_name = "home/update_grantgoal.html"
    model = GrantGoal
    form_class = UpdateGrantGoalForm
    success_url = reverse_lazy("home:index")
    success_message = "The Grant Goal Was Updated! ..."
    


class DeleteGrantGoal(generic.DeleteView):
    template_name = "home/delete_grantgoal.html"
    model = GrantGoal
    success_url = reverse_lazy("home:index")


###################### GOAL'S CRUD ############################### 

## Retrieve: List
class ListGoal(generic.View):
    template_name = "home/list_goal.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "goals": Goal.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)


class DetailGoal(generic.DetailView):
    template_name = "home/detail_goal.html"
    model = Goal



class FullCalendarGG(generic.View):
    template_name = "fullcalendar/fullcalendar.html"
    context = {}

    def get(self, request):
        self.context = {
            "grant_goals": GrantGoal.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)



##### LOGIN LOGOUT SIGNUP #####

class Logout(generic.View):
    def get(self, request):
        logout(request)
        return render(request, "home/index.html", {})



class SignUp(generic.CreateView):
    template_name = "home/signup.html"
    model = User
    form_class = UserForm
    success_url = reverse_lazy("home:index")

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password1 = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password1)
        if user is not None:
            login(self.request, user)
        return redirect("home:index")

# context = {
#     "pacientes": Citas.objects.filter(medico=request.user, turno=turno)
# }



# class Login(generic.View):
#     template_name = "home/index.html"
#     context = {}
#     form_class = LoginForm

#     def get(self, request):
#         self.context = {
#             "form": self.form_class
#         }
#         return render(request, self.template_name, self.context)

templates/home/about.html
{% extends 'base/base.html'%}

{% block title %}ABOUT {% endblock %}

{% block content %}

    <h1>Hola Mundo, XD soy About</h1>

    <h2>{{ param }}</h2>

{% endblock content%}

templates/home/delete_grantgoal.html
{% extends 'base/base.html' %}

{% block title %}Delete GrantGoal {% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <h3>¿Deseas eliminar el Objetivo Estrategico con nombre: {{ object }} ?</h3>
        <a href="{% url 'home:index' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
{% endblock content %}

templates/home/detail_goal.html
{% extends 'base/base.html' %}

{% block title %}Detail Goal{% endblock title %}

{% block content %}
    <div class="accordion" id="accordionExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              Elementary Data
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
            <div class="accordion-body">
              This is the Goal Name: <strong> {{object.goal_name}} </strong>
              <hr>
              <p>{{ object.description }}</p>
              En seguimiento del GrantGoal: <strong>{{ object.grant_goal }}</strong>, autorizado by: {{ object.user }}
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              Time Data
            </button>
          </h2>
          <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <strong>This Goal has the next Duration: {{ object.duration }} days.</strong> 
              <p>You can do it, just doi, think different y otras cosas motivacionales You can do it, just doi, think different y otras cosas motivacionales You can do it, just doi, think different y otras cosas motivacionales You can do it, just doi, think different y otras cosas motivacionales</p>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingThree">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              Status Data
            </button>
          </h2>
          <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
            <div class="accordion-body">
             State for This Goal:  <strong> {{ object.state}}.</strong> 
             Status for this Goal: {% if object.status %} Este Goal aun tiene status activo {% else %} Este Gaol ya esta cerrado {% endif %}
             <hr>
             Timestamp for this Goal: {{ object.timestamp }}
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

templates/home/detail_grant_goal.html
{% extends 'base/base.html' %}

{% block title %}Detail Grant Goal{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Elementary Data
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
        <div class="accordion-body">
          This is the Goal Name: <strong> {{ grant_goal }} </strong>
          <hr>
          <p>{{ grant_goal.description }}</p>
          En seguimiento del GrantGoal: <strong>{{ grant_goal }}</strong>, autorizado by: {{ grant_goal.user }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Time Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This Goal has the next Duration: {{ grant_goal.days_duration }} days.</strong> 
          <p>You can do it, just doi, think different y otras cosas motivacionales You can do it, just doi, think different y otras cosas motivacionales You can do it, just doi, think different y otras cosas motivacionales You can do it, just doi, think different y otras cosas motivacionales</p>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Status Data
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
         State for This Goal:  <strong> {{ grant_goal.state}}.</strong> 
         Status for this Goal: {% if grant_goal.status %} Este Grant Goal aun tiene status activo {% else %} Este Grant Goal ya esta cerrado {% endif %}
         <hr>
         Timestamp for this Goal: {{ grant_goal.timestamp }}
        </div>
      </div>
    </div>
  </div>
    
    <br>

    <a href="{% url 'home:index' %}" class="btn btn-outline-info form-control">Back</a>
{% endblock content %}

templates/home/index.html
{% extends 'base/base.html'%}

{% block title %}Index APP {% endblock title %}

{% block content %}
   
{% if request.user.is_authenticated %}
    <h2>Bienvenido {{request.user }} </h2>
    <a href="{% url 'home:logout' %}">LogOut</a>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>GOAL TITLE</th>
            <th>USER</th>
            <th>TIMESTAMP</th>
            <th>STATUS</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for obj in grant_goals %}
                <tr>
                    <td>{{ obj.id }}</td>
                    <td>{{ obj.goal_title }}</td>
                    <td>{{ obj.user }}</td>
                    <td>{{ obj.timestamp }}</td>
                    <td>{{ obj.status }}</td>
                    <td><a href="{% url 'home:detail_grant_goal' obj.id %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'home:update_grant_goal' obj.id %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'home:delete_grant_goal' obj.id %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% else %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}
            <a href="{% url 'home:index' %}" class="btn btn-outline-warning">Cancel</a>
            <button type="submit" class="btn btn-outline-primary">LogIn</button>
        </form>
        Si no tienes una cuenta registrate <a href="{% url 'home:signup' %}">Aqui</a>
    {% endif %}

{% endblock content %}

templates/home/list_goal.html
{% extends 'base/base.html'%}

{% block title %}Goal's List{% endblock title %}

{% block content %}
   

    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>GOAL NAME</th>
            <th>USER</th>
            <th>TIMESTAMP</th>
            <th>STATUS</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for obj in goals %}
                <tr>
                    <td>{{ obj.id }}</td>
                    <td>{{ obj.goal_name }}</td>
                    <td>{{ obj.user }}</td>
                    <td>{{ obj.timestamp }}</td>
                    <td>{{ obj.status }}</td>
                    <td><a href="{% url 'home:detail_goal' obj.id %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}

templates/home/new_grantgoal.html
{% extends 'base/base.html' %}

{% block title %}New Grant Goal{% endblock title %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <p {% if message.tags == "success" %} class="alert alert-success" {% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}
    <form action="" method="post" class="form">
        {% csrf_token %}
            {{ form.as_p }}
        <a href="{% url 'home:index' %}" class="btn btn-outline-warning">Cancel</a>
        <button type="submit" class="btn btn-outline-success">Save</button>
    </form>
{% endblock content %}

templates/home/signup.html
{% extends "base/base.html" %}

{% block title %}
  SIGNUP VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success form-control">SIGNUP</button>
        <a href="{% url 'home:index' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/home/update_grantgoal.html
{% extends 'base/base.html' %}

{% block title %}Update Grant Goal{% endblock title %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <p {% if message.tags == "success" %} class="alert alert-danger" {% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        
        <a href="{% url 'home:index' %}" class="btn btn-outline-warning form-control mt-3">Cancel</a>
        <button type="submit" class="btn btn-outline-success form-control mt-3 mb-3">Update</button>
    
    </form>
{% endblock content %}