api/urls.py
from django.urls import path

from api import views

app_name = "api"


urlpatterns = [
    ##### CLIENTS #####
    path('ws/grantgoal/list', views.wsListGrantGoal, name="ws_grantgoal"),
    path('client/grantgoal/create/', views.CreateGrantGoalClient.as_view(), name="client_grantgoal_create"),
    path('client/grantgoal/', views.ListGrantGoalClient.as_view(), name="client_grantgoal"),
    path('client/grantgoal/detail/<str:gname>/', views.DetailGrantGoalClient.as_view(), name="client_detail"),
    path('client/grantgoal/update/<int:pk>/', views.UpdateGrantGoalClient.as_view(), name="client_update"),

    ###### V2 API #####
    path('v3/create/grantgoal/', views.CreateGrantGoal.as_view(), name="create_grantgoal"),
    path('v2/list/grant_goals/', views.ListGrantGoal.as_view(), name="list_grantgoals"),
    path('v2/detail/grant_goal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_grantgoal"),
    path('v3/update/grant_goal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_grantgoal"),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"


urlpatterns = [
    
    path('new_grant_goal/', views.NewGrantGoal.as_view(), name="new_grant_goal"),
    path('update_grant_goal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_grant_goal"),
    path('detail_grant_goal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_grant_goal"),
    path('delete_grant_goal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="delete_grant_goal"),
    #### GOAL'S URLS
    path('goal/list/', views.ListGoal.as_view(), name="list_goal"),
    path('goal/detail/<int:pk>/', views.DetailGoal.as_view(), name="detail_goal"),

    ### FULL CALENDAR URL'S
    path('fullcalendar/', views.FullCalendarGG.as_view(), name="fullcalendar"),

    #### AUTHENTICATE SYSTEM URLS ####
    path('logout/', views.Logout.as_view(), name="logout"),
    path('', views.Index.as_view(), name="index"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

sysplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('api/', include("api.urls")),
]

templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href= "{% static 'fullcalendar/main.css'%}" rel='stylesheet' />
    {% block fullcalendar %}{% endblock fullcalendar %}
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:fullcalendar' %}">FullCalendar</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Actions
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{%url 'home:new_grant_goal' %}">New Grant Goal</a></li>
                  <li><a class="dropdown-item" href="{% url 'home:list_goal' %}">Goal's</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
  
      {% block content %}
      {% endblock content %}
    </div>
    
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'fullcalendar/main.js' %}"></script>
  </body>
</html>