api/urls.py
from django.urls import path

from api import views

app_name = "api"


urlpatterns = [
    ##### CLIENTS #####
    path('ws/grantgoal/list', views.wsListGrantGoal, name="ws_grantgoal"),
    path('client/grantgoal/create/', views.CreateGrantGoalClient.as_view(), name="client_grantgoal_create"),
    path('client/grantgoal/', views.ListGrantGoalClient.as_view(), name="client_grantgoal"),
    path('client/grantgoal/detail/<str:gname>/', views.DetailGrantGoalClient.as_view(), name="client_detail"),
    path('client/grantgoal/update/<int:pk>/', views.UpdateGrantGoalClient.as_view(), name="client_update"),

    ###### V2 API #####
    path('v3/create/grantgoal/', views.CreateGrantGoal.as_view(), name="create_grantgoal"),
    path('v2/list/grant_goals/', views.ListGrantGoal.as_view(), name="list_grantgoals"),
    path('v2/detail/grant_goal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_grantgoal"),
    path('v3/update/grant_goal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_grantgoal"),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"


urlpatterns = [
    
    path('new_grant_goal/', views.NewGrantGoal.as_view(), name="new_grant_goal"),
    path('update_grant_goal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_grant_goal"),
    path('detail_grant_goal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_grant_goal"),
    path('delete_grant_goal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="delete_grant_goal"),
    #### GOAL'S URLS
    path('goal/list/', views.ListGoal.as_view(), name="list_goal"),
    path('goal/detail/<int:pk>/', views.DetailGoal.as_view(), name="detail_goal"),

    ### FULL CALENDAR URL'S
    path('fullcalendar/', views.FullCalendarGG.as_view(), name="fullcalendar"),

    #### AUTHENTICATE SYSTEM URLS ####
    path('logout/', views.Logout.as_view(), name="logout"),
    path('', views.Index.as_view(), name="index"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

sysplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('api/', include("api.urls")),
]

api/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.



STATE = (
    ('DN', 'Done'),
    ('DG', 'Doing'),
    ('NS', 'NoStared'),
)


class GrantGoal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    goal_title = models.CharField(max_length=128)
    description = models.TextField(max_length=256)
    timestamp = models.DateField(auto_now_add=True,auto_now=False)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    status = models.BooleanField(default=True)
    state = models.CharField(max_length=16, choices=STATE, default="None")
    sprint = models.FloatField(default=0.0)
    slug = models.SlugField(max_length=128)

    def __str__(self):
        return self.goal_title
    
    # def save(self, *args, **kwargs):
    #     self.final_date = self.timestamp + timedelta(days=self.days_duration)
    #     super().save(*args, **kwargs)


## SIGNALS 
### post_save
@receiver(post_save, sender=GrantGoal)
def end_time_grantgoal(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()



GSTATE = (
    ('DNG', 'Done'),
    ('DGG', 'Doing'),
    ('NSG', 'NoStared'),
)

class Goal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    asigned_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='gasigned_user')## Pendiente de revisar y modificar
    grant_goal = models.ForeignKey(GrantGoal, on_delete=models.CASCADE)
    goal_name = models.CharField(max_length=128, default="Pretty Cool Goal")
    description = models.TextField(max_length=256)
    timestamp = models.DateField(auto_now_add=True)
    duration = models.IntegerField(default=1)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    status = models.BooleanField(default=True)
    state = models.CharField(max_length=16, choices=GSTATE, default="None")
    slug = models.SlugField(max_length=32)

    def __str__(self):
        return self.goal_name
    

@receiver(post_save, sender=Goal)
def end_time_goal(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.duration)
        instance.save()




SUBSTATE = (
    ('DNS', 'Done'),
    ('DGS', 'Doing'),
    ('NSS', 'NoStared'),
)

class SubGoal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    asigned_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sasigned_user')## Pendiente de revisar y modificar
    goal = models.ForeignKey(Goal, on_delete=models.CASCADE)
    subgoal_name = models.CharField(max_length=128, default="Pretty Cool SubGoal")
    description = models.TextField(max_length=256)
    timestamp = models.DateField(auto_now_add=True)
    duration = models.IntegerField(default=1)
    final_date = models.DateField(auto_now_add=False)
    status = models.BooleanField(default=True)
    state = models.CharField(max_length=16, choices=SUBSTATE, default="None")
    slug = models.SlugField(max_length=32)

    def __str__(self):
        return self.subgoal_name


TSTATE = (
    ('DT', 'Done'),
    ('DGT', 'Doing'),
    ('NST', 'NoStared'),
)

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    asigned_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasigned_user')## Pendiente de revisar y modificar
    subgoal = models.ForeignKey(SubGoal, on_delete=models.CASCADE)
    task_name = models.CharField(max_length=128, default="Pretty Cool SubGoal")
    description = models.TextField(max_length=256)
    timestamp = models.DateField(auto_now_add=True)
    duration = models.IntegerField(default=1)
    final_date = models.DateField(auto_now_add=False)
    status = models.BooleanField(default=True)
    state = models.CharField(max_length=16, choices=TSTATE, default="None")
    slug = models.SlugField(max_length=32)

    def __str__(self):
        return self.task_name

api/forms.py
from django import forms


from .models import GrantGoal

class CreateGrantGoalForm(forms.ModelForm):
    class Meta:
        model = GrantGoal
        fields = [
            "user",
            "goal_title",
            "description",
            "days_duration",
            "state",
            "sprint",
            "status",
            "slug"
        ]
        widgets = {
            "user": forms.Select(attrs={"class":"form-select", "placeholder": "Seleccione un User"}),
            "goal_title": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Nombre del Grant Goal"}),
            "description": forms.Textarea(attrs={"class":"form-control", "cols":"5", "type":"text"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-select"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-select"}),
            "sprint": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control"})
        }

api/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.core import serializers
from django.views import generic
import requests

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics

# Create your views here.
from .models import GrantGoal
from .forms import CreateGrantGoalForm
from .serializers import GrantGoalSerializer


def wsListGrantGoal(request):
    queryset = GrantGoal.objects.all()
    data = serializers.serialize('json', queryset)
    return HttpResponse(data, content_type='application/json')


### CREATE
class CreateGrantGoal(generics.CreateAPIView):
    serializer_class = GrantGoalSerializer
   


## RETRIEVE


class ListGrantGoal(APIView):
    def get(self, request, *args, **kwargs):
        grant_goals = GrantGoal.objects.filter(status=True)
        data = GrantGoalSerializer(grant_goals, many=True).data
        return Response(data)


class DetailGrantGoal(APIView):
    def get(self, request, pk, *args, **kwargs):
        grantgoal = GrantGoal.objects.get(pk=pk)
        data = GrantGoalSerializer(grantgoal).data
        return Response(data)



### UPDATE
class UpdateGrantGoal(generics.UpdateAPIView):
    serializer_class = GrantGoalSerializer
    queryset = GrantGoal.objects.all()

### DELETE



##### CLIENTS #####


### CREATE
class CreateGrantGoalClient(generic.View):
    template_name = "api/client_create_gg.html"
    context = {}
    url = "http://localhost:8000/api/v3/create/grantgoal/"
    form_class = CreateGrantGoalForm()
    response = ""

    def get(self, request):
        self.context = {
            "form": self.form_class
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request, *args, **kwargs):
        payload = {
            "goal_title": request.POST["goal_title"],
            "description": request.POST["description"],
            "days_duration": request.POST["days_duration"],  
            "status": request.POST["status"],
            "state": request.POST["state"],
            "sprint": request.POST["sprint"],
            "slug": request.POST["slug"],
            "user": request.POST["user"]
        }
        self.response = requests.post(url=self.url, data=payload)
        print(self.response)
        return redirect("/api/client/grantgoal")


### RETRIEVE
class ListGrantGoalClient(generic.View):
    template_name = "api/client.html"
    context = {}
    # url = "http://localhost:8000/api/v1/ws/grantgoal/list"
    url = "http://localhost:8000/api/v2/list/grant_goals/"
    def get(self, request):
        response = requests.get(url=self.url)
        #objects = response.json()
        self.context = {
            "list_grantgoal": response.json()
        }
        return render(request, self.template_name, self.context)
    


class DetailGrantGoalClient(generic.View):
    template_name = "api/client_detail.html"
    context = {}
    # url = "http://localhost:8000/api/v1/ws/grantgoal/list"
    url = "http://localhost:8000/api/v2/detail/grant_goal/"
    def get(self, request, gname, *args, **kwargs):
        self.url = self.url + f"{gname}/"
        print("-------",self.url)
        response = requests.get(url=self.url)
        self.context = {
            "grantgoal": response.json()
        }
        return render(request, self.template_name, self.context)


### UPDATE
class UpdateGrantGoalClient(generic.View):
    template_name = "api/client_update.html"
    context = {}
    url_get = "http://localhost:8000/api/v2/detail/grant_goal/"
    url_put = "http://localhost:8000/api/v3/update/grant_goal/"
    response = ""


    def get(self, request, pk):
        self.url_get = self.url_get + f"{pk}/"
        self.response = requests.get(url=self.url_get)
        self.context = {
            "grantgoal": self.response.json()
        }
        return render(request, self.template_name, self.context)

    def post(self, request, pk):
        self.url_put = self.url_put + f"{pk}/"
        payload = {            
            "user": request.POST["user"],
            "goal_title": request.POST["goal_title"],
            "description": request.POST["description"],
            "days_duration": request.POST["days_duration"],
            "status": request.POST["status"],
            "state": request.POST["state"],
            "sprint": request.POST["sprint"],
            "slug": request.POST["slug"]
        }
        print("------", self.url_put)
        self.response = requests.put(url=self.url_put, data=payload)
        return render(request, self.template_name, self.context)
### DELETE


    

templates/api/client.html
{% extends "base/base.html" %}

{% block title %}Client Grant Goal View{% endblock title %}

{% block content %}
    <a href="{% url 'api:client_grantgoal_create' %}" class="btn btn-outline-success form-control">Create a New GrantGoal</a>
    <table class="table">
                <thead>
                    <th>GRANTGOAL TITLE</th>
                    <th>TIMESTAMP</th>
                    <th>DURATION</th>
                    <th></th>
                    <th>ACTIONS</th>
                    <th></th>
                </thead>
                <tbody>
                {% for gg in list_grantgoal %}
                    <tr>
                        <td>{{ gg.goal_title }}</td>
                        <td>{{ gg.timestamp }}</td>
                        <td>{{ gg.days_duration }}</td>
                        <td><a href="{% url 'api:client_detail' gg.goal_title %}" class="btn btn-outline-info">Detail</a></td>
                        <td><a href="{% url 'api:client_update' gg.id %}" class="btn btn-outline-warning">Update</a></td>
                        <td><a href="" class="btn btn-outline-danger">Delete</a></td>
                    </tr>
                {% endfor %}
                </tbody>
    </table>
    
{% endblock content %}

templates/api/client_create_gg.html
{% extends "base/base.html" %}

{% block title %}
   CREATE GRANT GOAL VIEW
{% endblock title %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Create GrantGoal</button>
        <a href="{% url 'api:client_grantgoal' %}" class="btn btn-outline-warning">Cancel</a>
  </form>
{% endblock content %}

templates/api/client_detail.html
{% extends "base/base.html" %}

{% block title %}Client Grant Goal View{% endblock title %}

{% block content %}
   <div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Elementary Data
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
        <div class="accordion-body">
          This is the Goal Name: <strong> {{ grantgoal.goal_title }} </strong>
          <hr>
          <p>{{ grantgoal.description }}</p>
          En seguimiento del GrantGoal: <strong>{{ grantgoal.goal_title }}</strong>, autorizado by: {{ grantgoal.user }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Time Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This Goal has the next Duration: {{ grantgoal.days_duration }} days.</strong> 
          <p>You can do see de final date for the grantgoal {{ grantgoal.final_date }}, just doi, think different y otras cosas motivacionales You can do it, just doi, think different y otras cosas motivacionales You can do it, just doi, think different y otras cosas motivacionales You can do it, just doi, think different y otras cosas motivacionales</p>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Status Data
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
         State for This Goal:  <strong> {{ grantgoal.state}}.</strong> 
         Status for this Goal: {% if grantgoal.status %} Este Grant Goal aun tiene status activo {% else %} Este Grant Goal ya esta cerrado {% endif %}
         <hr>
         Timestamp for this Goal: {{ grantgoal.timestamp }}
        </div>
      </div>
    </div>
  </div>
    
    <br>

    <a href="{% url 'home:index' %}" class="btn btn-outline-info form-control">Back</a>

    
{% endblock content %}

templates/api/client_update.html
{% extends "base/base.html" %}

{% block title %}
  UPDATE GRANT GOAL VIEW CLIENT
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        <label for="user">User</label>
        <input type="select" class="form-control form-select" name="user" id="user" value="{{ grantgoal.user }}">
        <label for="goal_title">Grant Goal Title</label>
        <input type="text" class="form-control" name="goal_title" id="goal_title" value="{{ grantgoal.goal_title }}">
        <label for="description">Description</label>
        <input type="text" class="form-control" name="description" id="description" value="{{ grantgoal.description }}">
        <label for="days_duration">Days Duration</label>
        <input type="number" class="form-control" name="days_duration" id="days_duration" value="{{ grantgoal.days_duration }}">
        <label for="status">Status</label>
        <input type="checkbox" class="form-checkbox" name="status" id="status" value="{{ grantgoal.status }}">
        <label for="state">State</label>
        <input type="select" class="form-select" name="state" id="state" {% if grantgoal.state %} checked {% endif %}>
        <label for="sprint">Sprint</label>
        <input type="number" class="form-control" name="sprint" id="sprint" value="{{ grantgoal.sprint }}">
        <label for="slug">Slug</label>
        <input type="text" class="form-control" name="slug" id="slug" value="{{ grantgoal.slug }}">
        <button type="submit" class="btn btn-outline-primary form-control">Update Grant Goal</button>
        <a href="{% url 'api:client_grantgoal' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}